export type AudioSampleClip = {
  soundId: string
  text: string
  kind: 'letter' | 'hold' | 'syllable' | 'word'
  src: string
  ttsText?: string
  ready?: boolean
}

export const AUDIO_SAMPLE_CLIPS: AudioSampleClip[] = [
  { soundId: "he_letter_alef", text: "א", kind: "letter", src: "/audio/samples/he_letter_alef.mp3", ttsText: "אָלֶף" },
  { soundId: "he_letter_bet", text: "ב", kind: "letter", src: "/audio/samples/he_letter_bet.mp3", ttsText: "בֶּת" },
  { soundId: "he_letter_dalet", text: "ד", kind: "letter", src: "/audio/samples/he_letter_dalet.mp3", ttsText: "דָּלֶת" },
  { soundId: "he_letter_gimel", text: "ג", kind: "letter", src: "/audio/samples/he_letter_gimel.mp3", ttsText: "גִי מֶל" },
  { soundId: "he_letter_he", text: "ה", kind: "letter", src: "/audio/samples/he_letter_he.mp3", ttsText: "הֵא" },
  { soundId: "he_letter_het", text: "ח", kind: "letter", src: "/audio/samples/he_letter_het.mp3", ttsText: "חֵית" },
  { soundId: "he_letter_lamed", text: "ל", kind: "letter", src: "/audio/samples/he_letter_lamed.mp3", ttsText: "לָמֶד" },
  { soundId: "he_letter_mem", text: "מ", kind: "letter", src: "/audio/samples/he_letter_mem.mp3", ttsText: "מֵם" },
  { soundId: "he_letter_tet", text: "ט", kind: "letter", src: "/audio/samples/he_letter_tet.mp3", ttsText: "טֵית" },
  { soundId: "he_letter_vav", text: "ו", kind: "letter", src: "/audio/samples/he_letter_vav.mp3", ttsText: "וָו" },
  { soundId: "he_letter_yod", text: "י", kind: "letter", src: "/audio/samples/he_letter_yod.mp3", ttsText: "יִי" },
  { soundId: "he_letter_zayin", text: "ז", kind: "letter", src: "/audio/samples/he_letter_zayin.mp3", ttsText: "זַיִן" },
  { soundId: "he_hold_letter_alef", text: "אַ אַ אַ אַ", kind: "hold", src: "/audio/samples/he_hold_letter_alef.mp3" },
  { soundId: "he_hold_letter_bet", text: "בְּ בְּ בְּ בְּ", kind: "hold", src: "/audio/samples/he_hold_letter_bet.mp3" },
  { soundId: "he_hold_letter_dalet", text: "דְּ דְּ דְּ דְּ", kind: "hold", src: "/audio/samples/he_hold_letter_dalet.mp3" },
  { soundId: "he_hold_letter_gimel", text: "גְּ גְּ גְּ גְּ", kind: "hold", src: "/audio/samples/he_hold_letter_gimel.mp3" },
  { soundId: "he_hold_letter_he", text: "הְ הְ הְ הְ", kind: "hold", src: "/audio/samples/he_hold_letter_he.mp3" },
  { soundId: "he_hold_letter_het", text: "חְ חְ חְ חְ", kind: "hold", src: "/audio/samples/he_hold_letter_het.mp3" },
  { soundId: "he_hold_letter_lamed", text: "לְ לְ לְ לְ", kind: "hold", src: "/audio/samples/he_hold_letter_lamed.mp3" },
  { soundId: "he_hold_letter_mem", text: "מְ מְ מְ מְ", kind: "hold", src: "/audio/samples/he_hold_letter_mem.mp3" },
  { soundId: "he_hold_letter_tet", text: "טְ טְ טְ טְ", kind: "hold", src: "/audio/samples/he_hold_letter_tet.mp3" },
  { soundId: "he_hold_letter_vav", text: "וְ וְ וְ וְ", kind: "hold", src: "/audio/samples/he_hold_letter_vav.mp3" },
  { soundId: "he_hold_letter_yod", text: "יְ יְ יְ יְ", kind: "hold", src: "/audio/samples/he_hold_letter_yod.mp3" },
  { soundId: "he_hold_letter_zayin", text: "זְ זְ זְ זְ", kind: "hold", src: "/audio/samples/he_hold_letter_zayin.mp3" },
  { soundId: "he_syllable_alef_hiriq", text: "אִ", kind: "syllable", src: "/audio/samples/he_syllable_alef_hiriq.mp3", ttsText: "אִי" },
  { soundId: "he_syllable_alef_patah", text: "אַ", kind: "syllable", src: "/audio/samples/he_syllable_alef_patah.mp3", ttsText: "אָ" },
  { soundId: "he_syllable_alef_qamats", text: "אָ", kind: "syllable", src: "/audio/samples/he_syllable_alef_qamats.mp3" },
  { soundId: "he_syllable_alef_segol", text: "אֶ", kind: "syllable", src: "/audio/samples/he_syllable_alef_segol.mp3" },
  { soundId: "he_syllable_alef_tsere", text: "אֵ", kind: "syllable", src: "/audio/samples/he_syllable_alef_tsere.mp3" },
  { soundId: "he_syllable_bet_hiriq", text: "בִ", kind: "syllable", src: "/audio/samples/he_syllable_bet_hiriq.mp3", ttsText: "בִי" },
  { soundId: "he_syllable_bet_patah", text: "בַ", kind: "syllable", src: "/audio/samples/he_syllable_bet_patah.mp3", ttsText: "בָ" },
  { soundId: "he_syllable_bet_qamats", text: "בָ", kind: "syllable", src: "/audio/samples/he_syllable_bet_qamats.mp3" },
  { soundId: "he_syllable_dalet_hiriq", text: "דִ", kind: "syllable", src: "/audio/samples/he_syllable_dalet_hiriq.mp3", ttsText: "דִי" },
  { soundId: "he_syllable_dalet_holam", text: "דֹ", kind: "syllable", src: "/audio/samples/he_syllable_dalet_holam.mp3" },
  { soundId: "he_syllable_dalet_patah", text: "דַ", kind: "syllable", src: "/audio/samples/he_syllable_dalet_patah.mp3", ttsText: "דָ" },
  { soundId: "he_syllable_dalet_qamats", text: "דָ", kind: "syllable", src: "/audio/samples/he_syllable_dalet_qamats.mp3" },
  { soundId: "he_syllable_dalet_segol", text: "דֶ", kind: "syllable", src: "/audio/samples/he_syllable_dalet_segol.mp3" },
  { soundId: "he_syllable_dalet_tsere", text: "דֵ", kind: "syllable", src: "/audio/samples/he_syllable_dalet_tsere.mp3" },
  { soundId: "he_syllable_gimel_hiriq", text: "גִ", kind: "syllable", src: "/audio/samples/he_syllable_gimel_hiriq.mp3", ttsText: "גִי" },
  { soundId: "he_syllable_gimel_holam", text: "גֹ", kind: "syllable", src: "/audio/samples/he_syllable_gimel_holam.mp3" },
  { soundId: "he_syllable_gimel_patah", text: "גַ", kind: "syllable", src: "/audio/samples/he_syllable_gimel_patah.mp3", ttsText: "גָ" },
  { soundId: "he_syllable_gimel_qamats", text: "גָ", kind: "syllable", src: "/audio/samples/he_syllable_gimel_qamats.mp3" },
  { soundId: "he_syllable_gimel_segol", text: "גֶ", kind: "syllable", src: "/audio/samples/he_syllable_gimel_segol.mp3" },
  { soundId: "he_syllable_gimel_tsere", text: "גֵ", kind: "syllable", src: "/audio/samples/he_syllable_gimel_tsere.mp3" },
  { soundId: "he_syllable_he_hiriq", text: "הִ", kind: "syllable", src: "/audio/samples/he_syllable_he_hiriq.mp3", ttsText: "הִי" },
  { soundId: "he_syllable_he_holam", text: "הֹ", kind: "syllable", src: "/audio/samples/he_syllable_he_holam.mp3" },
  { soundId: "he_syllable_he_patah", text: "הַ", kind: "syllable", src: "/audio/samples/he_syllable_he_patah.mp3", ttsText: "הָ" },
  { soundId: "he_syllable_he_qamats", text: "הָ", kind: "syllable", src: "/audio/samples/he_syllable_he_qamats.mp3" },
  { soundId: "he_syllable_he_segol", text: "הֶ", kind: "syllable", src: "/audio/samples/he_syllable_he_segol.mp3" },
  { soundId: "he_syllable_he_tsere", text: "הֵ", kind: "syllable", src: "/audio/samples/he_syllable_he_tsere.mp3" },
  { soundId: "he_syllable_het_hiriq", text: "חִ", kind: "syllable", src: "/audio/samples/he_syllable_het_hiriq.mp3", ttsText: "חִי" },
  { soundId: "he_syllable_het_holam", text: "חֹ", kind: "syllable", src: "/audio/samples/he_syllable_het_holam.mp3" },
  { soundId: "he_syllable_het_patah", text: "חַ", kind: "syllable", src: "/audio/samples/he_syllable_het_patah.mp3", ttsText: "חָ" },
  { soundId: "he_syllable_het_qamats", text: "חָ", kind: "syllable", src: "/audio/samples/he_syllable_het_qamats.mp3" },
  { soundId: "he_syllable_het_segol", text: "חֶ", kind: "syllable", src: "/audio/samples/he_syllable_het_segol.mp3" },
  { soundId: "he_syllable_het_tsere", text: "חֵ", kind: "syllable", src: "/audio/samples/he_syllable_het_tsere.mp3" },
  { soundId: "he_syllable_lamed_hiriq", text: "לִ", kind: "syllable", src: "/audio/samples/he_syllable_lamed_hiriq.mp3", ttsText: "לִי" },
  { soundId: "he_syllable_lamed_holam", text: "לֹ", kind: "syllable", src: "/audio/samples/he_syllable_lamed_holam.mp3" },
  { soundId: "he_syllable_lamed_patah", text: "לַ", kind: "syllable", src: "/audio/samples/he_syllable_lamed_patah.mp3", ttsText: "לָ" },
  { soundId: "he_syllable_lamed_qamats", text: "לָ", kind: "syllable", src: "/audio/samples/he_syllable_lamed_qamats.mp3" },
  { soundId: "he_syllable_lamed_segol", text: "לֶ", kind: "syllable", src: "/audio/samples/he_syllable_lamed_segol.mp3" },
  { soundId: "he_syllable_lamed_tsere", text: "לֵ", kind: "syllable", src: "/audio/samples/he_syllable_lamed_tsere.mp3" },
  { soundId: "he_syllable_mem_hiriq", text: "מִ", kind: "syllable", src: "/audio/samples/he_syllable_mem_hiriq.mp3", ttsText: "מִי" },
  { soundId: "he_syllable_mem_patah", text: "מַ", kind: "syllable", src: "/audio/samples/he_syllable_mem_patah.mp3", ttsText: "מָ" },
  { soundId: "he_syllable_mem_qamats", text: "מָ", kind: "syllable", src: "/audio/samples/he_syllable_mem_qamats.mp3" },
  { soundId: "he_syllable_mem_segol", text: "מֶ", kind: "syllable", src: "/audio/samples/he_syllable_mem_segol.mp3" },
  { soundId: "he_syllable_tet_hiriq", text: "טִ", kind: "syllable", src: "/audio/samples/he_syllable_tet_hiriq.mp3", ttsText: "טִי" },
  { soundId: "he_syllable_tet_holam", text: "טֹ", kind: "syllable", src: "/audio/samples/he_syllable_tet_holam.mp3" },
  { soundId: "he_syllable_tet_patah", text: "טַ", kind: "syllable", src: "/audio/samples/he_syllable_tet_patah.mp3", ttsText: "טָ" },
  { soundId: "he_syllable_tet_qamats", text: "טָ", kind: "syllable", src: "/audio/samples/he_syllable_tet_qamats.mp3" },
  { soundId: "he_syllable_tet_qubuts", text: "טֻ", kind: "syllable", src: "/audio/samples/he_syllable_tet_qubuts.mp3", ttsText: "טוּ" },
  { soundId: "he_syllable_tet_segol", text: "טֶ", kind: "syllable", src: "/audio/samples/he_syllable_tet_segol.mp3" },
  { soundId: "he_syllable_tet_shuruk", text: "טוּ", kind: "syllable", src: "/audio/samples/he_syllable_tet_shuruk.mp3" },
  { soundId: "he_syllable_tet_tsere", text: "טֵ", kind: "syllable", src: "/audio/samples/he_syllable_tet_tsere.mp3" },
  { soundId: "he_syllable_vav_hiriq", text: "וִ", kind: "syllable", src: "/audio/samples/he_syllable_vav_hiriq.mp3", ttsText: "וִי" },
  { soundId: "he_syllable_vav_holam", text: "וֹ", kind: "syllable", src: "/audio/samples/he_syllable_vav_holam.mp3" },
  { soundId: "he_syllable_vav_patah", text: "וַ", kind: "syllable", src: "/audio/samples/he_syllable_vav_patah.mp3", ttsText: "וָ" },
  { soundId: "he_syllable_vav_qamats", text: "וָ", kind: "syllable", src: "/audio/samples/he_syllable_vav_qamats.mp3" },
  { soundId: "he_syllable_vav_qubuts", text: "וֻ", kind: "syllable", src: "/audio/samples/he_syllable_vav_qubuts.mp3", ttsText: "ווּ" },
  { soundId: "he_syllable_vav_segol", text: "וֶ", kind: "syllable", src: "/audio/samples/he_syllable_vav_segol.mp3" },
  { soundId: "he_syllable_vav_shuruk", text: "ווּ", kind: "syllable", src: "/audio/samples/he_syllable_vav_shuruk.mp3" },
  { soundId: "he_syllable_vav_tsere", text: "וֵ", kind: "syllable", src: "/audio/samples/he_syllable_vav_tsere.mp3" },
  { soundId: "he_syllable_yod_hiriq", text: "יִ", kind: "syllable", src: "/audio/samples/he_syllable_yod_hiriq.mp3", ttsText: "יִי" },
  { soundId: "he_syllable_yod_holam", text: "יֹ", kind: "syllable", src: "/audio/samples/he_syllable_yod_holam.mp3" },
  { soundId: "he_syllable_yod_patah", text: "יַ", kind: "syllable", src: "/audio/samples/he_syllable_yod_qamats.mp3", ttsText: "יָ" },
  { soundId: "he_syllable_yod_qamats", text: "יָ", kind: "syllable", src: "/audio/samples/he_syllable_yod_qamats.mp3" },
  { soundId: "he_syllable_yod_segol", text: "יֶ", kind: "syllable", src: "/audio/samples/he_syllable_yod_segol.mp3" },
  { soundId: "he_syllable_yod_tsere", text: "יֵ", kind: "syllable", src: "/audio/samples/he_syllable_yod_tsere.mp3" },
  { soundId: "he_syllable_zayin_hiriq", text: "זִ", kind: "syllable", src: "/audio/samples/he_syllable_zayin_hiriq.mp3", ttsText: "זִי" },
  { soundId: "he_syllable_zayin_holam", text: "זֹ", kind: "syllable", src: "/audio/samples/he_syllable_zayin_holam.mp3" },
  { soundId: "he_syllable_zayin_patah", text: "זַ", kind: "syllable", src: "/audio/samples/he_syllable_zayin_patah.mp3", ttsText: "זָ" },
  { soundId: "he_syllable_zayin_qamats", text: "זָ", kind: "syllable", src: "/audio/samples/he_syllable_zayin_qamats.mp3" },
  { soundId: "he_syllable_zayin_qubuts", text: "זֻ", kind: "syllable", src: "/audio/samples/he_syllable_zayin_qubuts.mp3", ttsText: "זוּ" },
  { soundId: "he_syllable_zayin_segol", text: "זֶ", kind: "syllable", src: "/audio/samples/he_syllable_zayin_segol.mp3" },
  { soundId: "he_syllable_zayin_shuruk", text: "זוּ", kind: "syllable", src: "/audio/samples/he_syllable_zayin_shuruk.mp3" },
  { soundId: "he_syllable_zayin_tsere", text: "זֵ", kind: "syllable", src: "/audio/samples/he_syllable_zayin_tsere.mp3" },
  { soundId: "he_word_alef-mem-alef", text: "אִמָא", kind: "word", src: "/audio/samples/he_word_alef-mem-alef.mp3" },
  { soundId: "he_word_bet-alef", text: "בָא", kind: "word", src: "/audio/samples/he_word_bet-alef.mp3" },
  { soundId: "he_word_dag-patah", text: "דַג", kind: "word", src: "/audio/samples/he_word_dag-patah.mp3" },
  { soundId: "he_word_halav-qamats", text: "חָלָב", kind: "word", src: "/audio/samples/he_word_halav-qamats.mp3" },
  { soundId: "he_word_he-yod-alef", text: "הִיא", kind: "word", src: "/audio/samples/he_word_he-yod-alef.mp3" },
  { soundId: "he_word_lamed-bet", text: "לֵב", kind: "word", src: "/audio/samples/he_word_lamed-bet.mp3" },
  { soundId: "he_word_mem-yod", text: "מִי", kind: "word", src: "/audio/samples/he_word_mem-yod.mp3" },
  { soundId: "he_word_yad-qamats", text: "יָד", kind: "word", src: "/audio/samples/he_word_yad-qamats.mp3" },
]
